# Generated by Django 4.1 on 2022-09-01 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0003_rename_subtaskid_steptask_subtask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptask',
            name='subtask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toDo.subtask'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toDo.task'),
        ),
    ]
