# Generated by Django 4.1 on 2022-09-01 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('task', models.ForeignKey(db_column='taskId', on_delete=django.db.models.deletion.CASCADE, to='toDo.task')),
            ],
        ),
        migrations.CreateModel(
            name='StepTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('levelPriority', models.CharField(max_length=100)),
                ('subtask', models.ForeignKey(db_column='subtaskId', on_delete=django.db.models.deletion.CASCADE, to='toDo.subtask')),
            ],
        ),
    ]
