# Generated by Django 4.1 on 2022-09-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steptask',
            old_name='subtask',
            new_name='subtaskId',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='task',
            new_name='taskId',
        ),
    ]
