# Generated by Django 4.1 on 2022-09-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0005_alter_steptask_end_alter_steptask_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptask',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='steptask',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
