FROM ubuntu:latest

WORKDIR /home

ADD backend /home
ADD .env /home/.env

RUN apt-get update
RUN apt-get install -y python3 pip libmysqlclient-dev
RUN pip install django
RUN pip install mysqlclient tzdata python-dotenv

CMD python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000
