FROM ubuntu:latest

WORKDIR /home

ADD backend /home

RUN apt-get update
RUN apt-get install -y python3 pip libmysqlclient-dev
RUN pip install django
RUN pip install mysqlclient

RUN python3 manage.py migrate

CMD python3 manage.py runserver 8000

EXPOSE 8000