version: '3.9'
services:
  web:
    build: ./web
    ports:
      - 8000:8000
    depends_on:
      - database
  
  database:
    build: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=todo